name: Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Check typos
        uses: crate-ci/typos@master
      - name: Check formatting
        run: just lint


  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: ["nightly"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust {{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run check
        run: just check clippy

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: ["nightly"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: just test-code test-docs
        env:
          RUST_BACKTRACE: full
